version: '3.8'

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    volumes:
      # ':delegated':
      # saves data to local machine in batches
      # slight performance improvement
      - ./src:/var/www/html:delegated 

  mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    env_file:
      - ./.env/.mysql.env
  
  # utility container to create Laravel app:
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html


  # artisan:
  # npm:
