### example of having
### multiple resource definitions
### in a singe file.
### individual resources
### must be separated by
### '---'
### yaml specific ^

### best practice:
### place service before deployment

apiVersion: v1
kind: Service
metadata:
  name: declarative-service

# configures service
spec:
  # selects pods to be controlled by service
  # can only select 'labels'
  selector:
    app: declarative-deployment-pod

  ports: # array
    - protocol: 'TCP'
      port: 80 # port exposed to the outside
      targetPort: 8080 # port container listens to

  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: declarative-deployment-v1

# configures deployment
spec:
  replicas: 3

  # selects pods to be controlled by deployment
  selector:
    matchLabels:
      app: declarative-deployment-pod

  # describes pods managed by deployment
  template:
    metadata:
      labels:
        app: declarative-deployment-pod

    # configures individual pods
    spec:
      containers: # array
        - name: declarative-deployment-container
          image: bkmetoff/k8-first-dep:v3
